### ISSUE TITLE
make "description" into a string array or string

### ISSUE THREAD

**Issue by darshakthakore** [json-schema/json-schema#226]
Currently the "description" property is a string-only just like title. However given the fact that the "description" can be used to explain enums and things like that, it would be good if the "description" can be made into either a string or a sting array, that way the following can be done
`
{
  "type": "string",
  "enum": [ "enum1", "enum2", "enum3" ],
  "description": [ "The value must be an enum where",
                          "enum1 - meaning of enum1",
                          "enum2 - meaning of enum2",
                          "enum3 - meaning of enum3"
                        ]                       
}
`
This will allow the "description" element to be more human friendly as well as machine usable.

**Comment by IvanGoncharov** [comment]
@darshakthakore Why you can use new line character inside `descriptions`, like
```
"The value must be an enum where\nenum1 - meaning of enum1\nenum2 - meaning of enum2\nenum3 - meaning of enum3"
```
If you speak about readability of raw JSON you can always convert it into the YAML:
```yaml
type: string
enum:
  - enum1
  - enum2
  - enum3
description: |
  The value must be an enum where
  enum1 - meaning of enum1
  enum2 - meaning of enum2
  enum3 - meaning of enum3
```
JSON is machine-friendly format and I don't think JSON Schema should solve this problem.
Instead you can use YAML format which is human-friendly to represent JSON Schema.
